### PR TITLE
Testing : upgrade to 1.21.0

### PR DESCRIPTION
**Pull request by lapineige**
#160

Manual testing needed before merging :)

### CODE REVIEW

**Comment by lapineige** [comment]
Upgrade went fine on my side, waiting for another feedback.

**Comment by lapineige** [comment]
Another manual testing in the forum went fine.
Let's merge ? @plopoyop :)

**Comment by lapineige** [comment]
Please merge @plopoyop 😉

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Ok CI is happy too, so I will take the liberty to merge :)

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
