### PR TITLE
Harden permissions

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
## Problem
-  They were too lax #115 

## Solution
- I hardened them. Now only `www-data` and `freshrss` can read `$final_path`, and only `freshrss` can write to the `extensions` and `data` dirs. I don't know if it's possible to improve on this

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

### CODE REVIEW

**Comment by Jules-Bertholet** [comment]
!testme

**Comment by plopoyop** [comment]
!testme

**Comment by plopoyop** [comment]
It is working on my test instance, I don't know why it did not pass last CI check

**Comment by Jules-Bertholet** [comment]
!testme

**Comment by Jules-Bertholet** [comment]
Tests passed!

**Comment by lapineige** [comment]
Then let's merge it :)

**Pull request merged**
