### PR TITLE
Update to v1.19.1

### PR DESCRIPTION
**Pull request by lapineige**
FreshRSS 1.19.0 is out https://github.com/FreshRSS/FreshRSS/releases/tag/1.19.0

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by krisu5** [comment]
BTW, 1.19.1 has been released too: https://github.com/FreshRSS/FreshRSS/releases/tag/1.19.1

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Merging directly into testing as this a the only and minor change.
I will run Continuous Integration there.

**Pull request merged**
