### PR TITLE
Update FreshRSS to 1.18.0

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
## Problem
- New version of FreshRSS released

## Solution
- Update to this new version

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
[Test Badge](https://ci-apps-dev.yunohost.org/ci/job/872)

### CODE REVIEW

**Comment by Jules-Bertholet** [comment]
!testme

**Comment by plopoyop** [comment]
LGTM
I'am waiting for the test to be run before merge.

**Comment by Jules-Bertholet** [comment]
!testme

**Comment by Jules-Bertholet** [comment]
!testme

**Comment by Jules-Bertholet** [comment]
It works!

**Comment by lapineige** [comment]
That's great ! Thanks for your work :)

**Pull request merged**
