### PR TITLE
fix missing application name

### PR DESCRIPTION
**Pull request by ashemsay**
## Problem
- *Adding or deleting users raises an error on freshrss post_user_create or post_user_delete scripts*

## Solution
- *Fix application path by setting the $app variable in post_user_create and post_user_delete hooks*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/freshrss_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by plopoyop** [comment]
This way to fix the bug would break the multi instance install.
It must be done the same way it is done in upgrade script : 

```#update hook for multi instance
ynh_replace_string "APPNAMETOCHANGE" $app ../hooks/post_app_addaccess
ynh_replace_string "APPNAMETOCHANGE" $app ../hooks/post_user_create
ynh_replace_string "APPNAMETOCHANGE" $app ../hooks/post_user_delete```

**Comment by ashemsay** [comment]
Indeed, I don't know anything about yunohost packaging, I'm glad I learned that, thanks :)

**Comment by youplaboum** [comment]
Then, what has to be changed in order to get the add user script working, without having to manually do this in cli ?

**Comment by plopoyop** [comment]
@youplaboum I did it in https://github.com/YunoHost-Apps/freshrss_ynh/pull/92

**Pull request closed without merging**
