### PR TITLE
Fixes for silent error with cron

### PR DESCRIPTION
**Pull request by xoddark**
## Problem
- cron silently failed after save/restore

## Solution
- write cron logs in folder app instead of /tmp/
- use MAILTO to send email to admin when script launched by cron have error instead of tried to send it to freshrss  

## PR Status
- [x] Code finished.
- [x] Fix or enhancement tested.
- [x] Can be reviewed and tested.

### CODE REVIEW

**Review by ericgaspar — APPROVED** [review]

**Comment by cheywood** [comment]
FWIW this didn't seem to fix the issue for me. A solution for me was changing the /etc/cron.d/freshrss ownership to root (from freshrss).

**Comment by xoddark** [comment]
> FWIW this didn't seem to fix the issue for me. A solution for me was changing the /etc/cron.d/freshrss ownership to root (from freshrss).

I think this is an other issue. Do you know why the freshrss ownerchip wasn't to root ?
I think the best is to have a corresponding bug.

**Comment by cheywood** [comment]
> > FWIW this didn't seem to fix the issue for me. A solution for me was changing the /etc/cron.d/freshrss ownership to root (from freshrss).
> 
> I think this is an other issue. Do you know why the freshrss ownerchip wasn't to root ?

No sorry I'm not sure what caused the ownership issue. In this case I'm just a user who played whack-a-mole to resolve it locally. But I didn't have any kind of special/custom environment which should might have caused this. 

> I think the best is to have an issue for this bug.

Sure thing, I'll aim to put up a separate issue.

**Review by lapineige — APPROVED** [review]

**Comment by lapineige** [comment]
Maybe we can fix #126 at the same time ?

**Pull request merged**
