### PR TITLE
Testing : version 1.23.1

### PR DESCRIPTION
**Pull request by lapineige**
#175

### CODE REVIEW

**Comment by lapineige** [comment]
Upgrading didn't work for me, I have a white screen afterwards.

This require manual testing...

**Comment by OniriCorpe** [comment]
maybe related to https://github.com/FreshRSS/FreshRSS/issues/5976

**Comment by Alkarex** [comment]
@lapineige Any logs?

**Comment by OniriCorpe** [comment]
I put this here:

**Environment information:**
- Device: 
- OS: Debian Bullseye
- Browser: 
- FreshRSS version: 1.23.0
- Database version: MariaDB 10.5.21-0+deb11u1
- PHP version: PHP 8.2
- Installation type: Yunohost
- Installed dependencies: [see here](https://github.com/YunoHost-Apps/freshrss_ynh/blob/master/manifest.toml#L74)

**Comment by lapineige** [comment]
> @lapineige Any logs?

Not that I could find.

**Comment by lapineige** [comment]
@Alkarex 
That file https://github.com/FreshRSS/FreshRSS/issues/5976#issuecomment-1869132178 content :
```
'extensions_enabled' => 
  array (
    'Google-Groups' => false,
    'Tumblr-GDPR' => false,
    'Invidious Video Feed' => true,
  ),
  'extensions' => 
  array (
  ),
```

**Comment by Alkarex** [comment]
@lapineige Your problem does not seem to be the same than https://github.com/FreshRSS/FreshRSS/issues/5976
A white screen most likely creates a log in your Web server logs and/or FreshRSS logs.

**Comment by lapineige** [comment]
Oh yes, this time (it wasn't the case before) I have this:
```
PHP Fatal error:  Uncaught TypeError: Minz_ExtensionManager::enable(): Argument #1 ($ext_name) must be of type string, int given, called in /var/www/freshrss/lib/Minz/ExtensionManager.php on line 279 and defined in /var/www/freshrss/lib/Minz/ExtensionManager.php:248
Stack trace:
#0 /var/www/freshrss/lib/Minz/ExtensionManager.php(279): Minz_ExtensionManager::enable()
#1 /var/www/freshrss/app/FreshRSS.php(63): Minz_ExtensionManager::enableByList()
#2 /var/www/freshrss/app/actualize_script.php(97): FreshRSS->init()
#3 {main}
  thrown in /var/www/freshrss/lib/Minz/ExtensionManager.php on line 248
Results:
```

**Comment by Alkarex** [comment]
Yes, same than https://github.com/FreshRSS/FreshRSS/issues/5976

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/5979

**Comment by Alkarex** [comment]
Would you be able to try FreshRSS `edge` version before we release version 1.23.1?

**Comment by lapineige** [comment]
Where is it available ? Could we have a branch pointing to that specific release ?

**Comment by Alkarex** [comment]
That is just the `edge` branch of https://github.com/FreshRSS/FreshRSS
Available by git, ZIP, tar...
ZIP: https://github.com/FreshRSS/FreshRSS/archive/latest.zip
You can also pick a specific commit if you like

**Comment by lapineige** [comment]
I see 1.3.1 is out, so we will wait for it :)

**Comment by lapineige** [comment]
Upgrade went fine in my case. Ready for merge.
ping @plopoyop

**Pull request merged**
