### PR TITLE
Testing : v1.20 + Bulleyes fixes

### LINKED ISSUE #75: pm.max_children limit reached
Hi,

while trying to understand why my freshrss cron is not running anymore I took a look at `/var/log/php7.0-fpm.log` and noticed this warning:

```bash
WARNING: [pool freshrss] server reached pm.max_children setting (5), consider raising it
```

I thought I should open a ticket so that issue might be fixed in the nginx configuration?

### PR DESCRIPTION
**Pull request by lapineige**
## Problem

- *Close #142*

## Solution

- *Apply last example_ynh*
- *Fix #75*
- New version 1.20 https://github.com/FreshRSS/FreshRSS/releases/tag/1.20.0

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by Alkarex** [comment]
FYI, by the end of the month, there will be a minor release 1.20.1 fixing a few bugs https://github.com/FreshRSS/FreshRSS/pulls?q=milestone%3A1.20.1+is%3Aclosed+is%3Apr

**Review by yalh76 — APPROVED** [review]
LGTM

**Comment by lapineige** [comment]
Ok then I'm ok to wait for that bug fix release. Meanwhile users can still use this version with the testing branch.

**Review by plopoyop — APPROVED** [review]

**Comment by lapineige** [comment]
This causes trouble https://forum.yunohost.org/t/probleme-avec-la-mise-a-jour-de-freshrss/21875 ?
> ““Cron <freshrss@p…56> /usr/bin/php7.4 /var/www/freshrss/app/actualize_script.php >/var/log/freshrss/freshrss.log 2>&1""
“”/bin/sh: 1: cannot create /var/log/freshrss/freshrss.log: Permission denied””

**Comment by yalh76** [comment]
> This causes trouble https://forum.yunohost.org/t/probleme-avec-la-mise-a-jour-de-freshrss/21875 ?
> 
> > ““Cron <freshrss@p…56> /usr/bin/php7.4 /var/www/freshrss/app/actualize_script.php >/var/log/freshrss/freshrss.log 2>&1""
> > “”/bin/sh: 1: cannot create /var/log/freshrss/freshrss.log: Permission denied””
> 
> @yalh76 I believe it's because of the change you made to the log file location (/var/www -> /var/log) and permission issues: https://github.com/YunoHost-Apps/freshrss_ynh/pull/146/files#diff-b6fe977119ccbe78ecd82239e9027e7ad39da209af7969156687d037bce754b0

Do you plan to rollback the change I made on `freshrss.cron`

**Comment by lapineige** [comment]
#150 fixed it :)

**Comment by 6-ril** [comment]
Hello, 
I'm using FressRss version1.20.0~ynh1.
Does the issue on the log ( Permission denied ) is supposed to be fixed ?

6-ril

**Pull request merged**
