### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by lapineige**
#123 
#125 
#127

## PR Status

Waiting for https://github.com/YunoHost-Apps/freshrss_ynh/pull/128

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by plopoyop** [comment]
!testme

**Review by plopoyop — APPROVED** [review]

**Comment by lapineige** [comment]
Oh, it's funny, it seems that I am no longer authorised to merge to the master branch 🤔
(I am not going to do it, I just realised that fact)

I would like to wait for #128 to fix that whole bunch of issues at the time :)

**Comment by plopoyop** [comment]
I update package version.
It looks good to me.

Is it ok for for you ?

**Comment by lapineige** [comment]
Oh, right, that's a good idea, I always forget it.

Looks fine :)

**Pull request merged**
